### ISSUE TITLE
Bug tracker

### ISSUE THREAD

**Issue by nicktehrany** [Krien/NVMeBenchmarks#18]
For later when publishing the repo, I'll open this issue to track the minor issues we need to clean up (I'll keep adding any other things I find, once done we can just mark them as done):

- [x] instructions in Readme for setting up the python requirements
```bash
python3 -m venv venv
source venv/bin/activate
pip install -r plot_requirements.txt
pip install -r plot_requirements_jupyter.txt
# then jupyter notebook
jupyter notebook
```

- [x] ~~There is some additional requirements for the analysis (`analysis/3d_plots.ipynb`)? I did the install above (plot_requirements.txt) still some import error.~~

![Screenshot_2023-01-18_11-10-04](https://user-images.githubusercontent.com/44246280/213144128-42e13773-262b-41f7-a53e-35dafabc8d35.jpeg)

- [x] `analysis/investigative_plots_ZNS.ipynb` is invalid 

![Screenshot_2023-01-18_11-10-44](https://user-images.githubusercontent.com/44246280/213144344-4986693f-013d-4b2e-ada5-163998357471.jpeg)
- [x] Instructions in Readme to generate example figures. (The plotting also has an error in it):

![Screenshot_2023-01-18_11-26-52](https://user-images.githubusercontent.com/44246280/213147835-ce595b68-2bfc-4275-98b2-bd696fd97d59.jpeg)

- [x] example_runs in its Readme say which devices names to change to what so the scripts could run locally.

- [x] Maybe something to depict the directory structure since there is quite a few directories here, and what to find where, what to run where to what purpose, etc.
